### ISSUE TITLE
drag forced to outermost corner on three monitor setup

### ISSUE THREAD

**Issue by castdrian** [gurinderhans/threefingerdrag#4]
for work I've got two monitors setup alongside my work notebook, everything works as expected on the main screen (middle) and it's right hand side counterpart. however attempting to drag anything on the left hand side screen (notebook) just forces the cursor into the outermost left corner

https://github.com/user-attachments/assets/134c1d5d-55f7-440b-8e93-3446914d1030

**Comment by gurinderhans** [comment]
Hi @castdrian, this exact issue was fixed in this commit: https://github.com/gurinderhans/ThreeFingerDrag/commit/4be6b92e4ca9f44bae63aecf08b7455ab568addf.

I can try later to create release build with above change, but in meantime, can you please build the latest code yourself? It should allow you to seamlessly drag across as many monitors as you have connected!
